// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3566.OfficialCode.subsystems;
import org.usfirst.frc3566.OfficialCode.RobotMap;
import org.usfirst.frc3566.OfficialCode.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc3566.OfficialCode.RobotConstants;
/**
 *
 */
public class Flipper extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController updownMotor = RobotMap.flipperUpdownMotor;
    DigitalInput upperCap = RobotMap.flipperUpperCap;
    DigitalInput lowerCap = RobotMap.flipperLowerCap;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void raise() {
        if (!atUpperLimit()) {
            updownMotor.set(RobotConstants.FLIPPER_RAISE_SPEED);
        }
    }
    
    public void lower() {
        if (!atLowerLimit()) {
            updownMotor.set(RobotConstants.FLIPPER_LOWER_SPEED);
        }
    }
    
    public void stop() {
        updownMotor.set(0);
    }
    
    public boolean atUpperLimit() {
        return upperCap.get() == RobotConstants.FLIPPER_UPPER_LIMIT_CLOSED;
    }
    
    public boolean atLowerLimit() {
        return lowerCap.get() == RobotConstants.FLIPPER_LOWER_LIMIT_CLOSED;
    }
}
