// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3566.OfficialCode.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3566.OfficialCode.Robot;
import org.usfirst.frc3566.OfficialCode.RobotMap;
import java.lang.Math;
/**
 *
 */
public class  AdjustX extends Command {
    public double targetang;
    public boolean isreached;
    public AdjustX() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.pIDDrive);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        isreached=false;
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.pIDDrive.angle = (RobotMap.server.getNumber("cogx")-320)*0.09375;
        targetang=Robot.pIDDrive.getGyro()+Robot.pIDDrive.angle;
        if (Robot.pIDDrive.getGyro()<targetang){
            Robot.pIDDrive.setright(0.35);
        }
        if (Robot.pIDDrive.getGyro()>targetang){
            Robot.pIDDrive.setleft(0.35);
        }
        if (Math.abs(RobotMap.server.getNumber("cogx")-320)<25){
            isreached=true;
        }
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isreached||this.timeSinceInitialized()==5;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
