// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3566.OfficialCode.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc3566.OfficialCode.Robot;
import org.usfirst.frc3566.OfficialCode.RobotMap;
/**
 *
 */
public class  AutonomousCommand extends CommandGroup {
    public AutonomousCommand() {
        
        
       
        addSequential(new StartShooter());
        addSequential(new AngleDown2());
        addParallel(new HockCloseOpen()); 
         
        //Shoot!!!
        addSequential(new DeckWheelOn());
        addSequential(new HockCloseOpen());
        
       
        addSequential(new DeckWheelOn());
        addSequential(new HockCloseOpen());
        
        addSequential(new DeckWheelOn());
        addSequential(new HockCloseOpen());
    }
    
}
